### ISSUE TITLE
Multiple file writes test timeout

### ISSUE THREAD

**Issue by denishowe** [amativos/node-storage#3]
The multiple file writes test times out unless I increase the timeout from 1.5s to 5s:
`mocha -r should -R spec -t 5000`
or reduce NUM_FILES from 500 to 150

node-storage 0.0.7
Node 9.4
Windows 7
Intel i7-3770 @ 3.4 GHz

Sorry for not having an SSD :-)

**Comment by amativos** [comment]
Yes, that was definitely a bad assumption :) Sorry about that.
